-- HEUBERT TRACKER - DATABASE SCHEMA

-- 1. Employees Table
CREATE TABLE IF NOT EXISTS employees (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  emp_no TEXT,
  dob DATE,
  joined_date DATE,
  left_date DATE,
  work_email TEXT,
  personal_email TEXT,
  phone TEXT,
  address TEXT,
  status TEXT DEFAULT 'active',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Late Fines Table
CREATE TABLE IF NOT EXISTS fines (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_name TEXT REFERENCES employees(name) ON DELETE CASCADE,
  date DATE NOT NULL,
  amount NUMERIC NOT NULL,
  status TEXT DEFAULT 'unpaid',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Leaves Table
CREATE TABLE IF NOT EXISTS leaves (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_name TEXT REFERENCES employees(name) ON DELETE CASCADE,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  type TEXT,
  reason TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Standup Records Table
CREATE TABLE IF NOT EXISTS standup_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_name TEXT REFERENCES employees(name) ON DELETE CASCADE,
  date DATE NOT NULL,
  status TEXT DEFAULT 'unpaid',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS) - Optional but recommended
-- For now, we will assume public access or simple API key access.
ALTER TABLE employees ENABLE ROW LEVEL SECURITY;
ALTER TABLE fines ENABLE ROW LEVEL SECURITY;
ALTER TABLE leaves ENABLE ROW LEVEL SECURITY;
ALTER TABLE standup_records ENABLE ROW LEVEL SECURITY;

-- Create Policies (Select all for anon)
CREATE POLICY "Public Read" ON employees FOR SELECT USING (true);
CREATE POLICY "Public Read" ON fines FOR SELECT USING (true);
CREATE POLICY "Public Read" ON leaves FOR SELECT USING (true);
CREATE POLICY "Public Read" ON standup_records FOR SELECT USING (true);

-- Create Policies (Insert/Update/Delete for anon - Adjust if you have Auth)
CREATE POLICY "Public Write" ON employees FOR ALL USING (true);
CREATE POLICY "Public Write" ON fines FOR ALL USING (true);
CREATE POLICY "Public Write" ON leaves FOR ALL USING (true);
CREATE POLICY "Public Write" ON standup_records FOR ALL USING (true);
