-- ATTENDANCE SYSTEM SCHEMA
-- Apply manually via the Supabase SQL editor (this project has no migration runner).

-- Singleton office/attendance configuration, admin-editable from either app
CREATE TABLE IF NOT EXISTS office_settings (
  id BIGINT PRIMARY KEY DEFAULT 1,
  latitude DOUBLE PRECISION NOT NULL,
  longitude DOUBLE PRECISION NOT NULL,
  radius_meters INT NOT NULL DEFAULT 200,
  late_fine_amount NUMERIC NOT NULL DEFAULT 50,
  sync_time TEXT NOT NULL DEFAULT '09:30', -- HH:MM, Asia/Kathmandu
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT single_row CHECK (id = 1)
);

INSERT INTO office_settings (id, latitude, longitude, radius_meters, late_fine_amount)
VALUES (1, 27.73810908379584, 85.31194375699422, 200, 50)
ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS attendance (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_name TEXT REFERENCES employees(name) ON DELETE CASCADE,
  date DATE NOT NULL,
  check_in_at TIMESTAMPTZ,
  check_in_lat DOUBLE PRECISION,
  check_in_lng DOUBLE PRECISION,
  check_out_at TIMESTAMPTZ,
  check_out_lat DOUBLE PRECISION,
  check_out_lng DOUBLE PRECISION,
  is_late BOOLEAN DEFAULT false,
  late_minutes INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (employee_name, date)
);

ALTER TABLE office_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE attendance ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public Read" ON office_settings FOR SELECT USING (true);
CREATE POLICY "Public Write" ON office_settings FOR ALL USING (true);
CREATE POLICY "Public Read" ON attendance FOR SELECT USING (true);
CREATE POLICY "Public Write" ON attendance FOR ALL USING (true);
