-- CONFIGURABLE LEAVE TYPES SCHEMA
-- Apply manually via the Supabase SQL editor (this project has no migration runner).

CREATE TABLE IF NOT EXISTS leave_types (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  annual_days NUMERIC NOT NULL DEFAULT 0,
  is_unpaid BOOLEAN NOT NULL DEFAULT false,
  is_active BOOLEAN NOT NULL DEFAULT true,
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE leaves ADD COLUMN IF NOT EXISTS leave_type_id BIGINT REFERENCES leave_types(id);

ALTER TABLE leave_types ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public Read" ON leave_types FOR SELECT USING (true);
CREATE POLICY "Public Write" ON leave_types FOR ALL USING (true);

INSERT INTO leave_types (name, annual_days, is_unpaid, sort_order) VALUES
  ('Personal Leave', 14, false, 1),
  ('Sick Leave', 4, false, 2),
  ('Festival Leave', 1, false, 3),
  ('Work From Home', 20, false, 4),
  ('Unpaid Leave', 30, true, 5)
ON CONFLICT (name) DO NOTHING;
