-- PROJECTS SCHEMA
-- Apply manually via the Supabase SQL editor (this project has no migration runner).

-- 1. Projects
CREATE TABLE IF NOT EXISTS projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  client TEXT,
  description TEXT,
  status TEXT NOT NULL DEFAULT 'active',
  tech_stack TEXT,
  start_date DATE,
  end_date DATE,
  created_by TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Project Links (repo, board, designs, docs, ...)
--    ON DELETE CASCADE: links are meaningless without their project.
CREATE TABLE IF NOT EXISTS project_links (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  label TEXT NOT NULL,
  url TEXT NOT NULL,
  category TEXT DEFAULT 'other',
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Project Environments (dev / stage / production / ...)
--    No credential columns on purpose — this table is world-readable under the
--    policies below, so secrets must never live here. `notes` is for pointers
--    ("creds in 1Password → Acme vault"), not for the credentials themselves.
CREATE TABLE IF NOT EXISTS project_environments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  url TEXT,
  branch TEXT,
  notes TEXT,
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS project_links_project_id_idx ON project_links(project_id);
CREATE INDEX IF NOT EXISTS project_environments_project_id_idx ON project_environments(project_id);

ALTER TABLE projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE project_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE project_environments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public Read" ON projects FOR SELECT USING (true);
CREATE POLICY "Public Read" ON project_links FOR SELECT USING (true);
CREATE POLICY "Public Read" ON project_environments FOR SELECT USING (true);

CREATE POLICY "Public Write" ON projects FOR ALL USING (true);
CREATE POLICY "Public Write" ON project_links FOR ALL USING (true);
CREATE POLICY "Public Write" ON project_environments FOR ALL USING (true);
