-- PUSH NOTIFICATIONS SCHEMA
-- Apply manually via the Supabase SQL editor (this project has no migration runner).

CREATE TABLE IF NOT EXISTS push_tokens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_name TEXT REFERENCES employees(name) ON DELETE CASCADE,
  expo_push_token TEXT NOT NULL UNIQUE,
  platform TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE push_tokens ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public Read" ON push_tokens FOR SELECT USING (true);
CREATE POLICY "Public Write" ON push_tokens FOR ALL USING (true);
